FROM alpine
RUN apk update && \
    apk add python3 uwsgi-python3 uwsgi-cgi uwsgi nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /var/www/index.html
COPY uwsgi_config.ini /etc/uwsgi_config.ini
COPY index.py /usr/lib/cgi-bin/index.py
EXPOSE 80
CMD /usr/sbin/uwsgi /etc/uwsgi_config.ini & /usr/sbin/nginx -c /etc/nginx/nginx.conf
